<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_UserProfile</name>
   <tag></tag>
   <elementGuidId>1461b8a4-d139-4b7b-ada4-62ed380470e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.euiAvatar.euiAvatar--s.euiAvatar--user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userMenuPopover']/div/button/span/span/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;User menu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>18ad2b75-0106-4f1e-9ff0-8265cb0e1838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiAvatar euiAvatar--s euiAvatar--user</value>
      <webElementGuid>310f082f-aa5d-45c9-90c1-a7992b7232be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>gpetras@ea.com</value>
      <webElementGuid>84c52ef8-39f1-494a-9935-cd4471f8bac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>gpetras@ea.com</value>
      <webElementGuid>47c1a0ff-3f81-4cf5-89c7-23a73c467e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userMenuPopover&quot;)/div[@class=&quot;euiPopover__anchor&quot;]/button[@class=&quot;euiButtonEmpty euiButtonEmpty--text euiHeaderSectionItemButton&quot;]/span[@class=&quot;euiButtonContent euiButtonEmpty__content&quot;]/span[@class=&quot;euiButtonEmpty__text&quot;]/span[@class=&quot;euiHeaderSectionItemButton__content&quot;]/div[@class=&quot;euiAvatar euiAvatar--s euiAvatar--user&quot;]</value>
      <webElementGuid>e91e12d7-3f5a-45f8-ad7f-ddc037ce6478</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userMenuPopover']/div/button/span/span/span/div</value>
      <webElementGuid>8f813e5d-4b16-4b6c-9749-9a2484584eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>c0028766-b1dd-485d-80e8-6d3b03b66177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'gpetras@ea.com']</value>
      <webElementGuid>979bffea-37e8-44a5-8a88-5aeac06c3400</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
