<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_UserPassword</name>
   <tag></tag>
   <elementGuidId>4694de9b-aeea-4dc3-bc1c-75e1cb1ca038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i7065ec41-05fc-11ef-adb4-ed4d7a2bca11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='i7065ec41-05fc-11ef-adb4-ed4d7a2bca11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Password input&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8540cc55-3f13-4934-b877-aeaa4b237c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bc020cfe-362e-4650-869d-3090ff41efe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i7065ec41-05fc-11ef-adb4-ed4d7a2bca11</value>
      <webElementGuid>b876eca6-41cc-4753-a284-2344e1aa035d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>980d6ceb-a3a0-49e4-94cc-1486df4b8c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldPassword</value>
      <webElementGuid>33dfe1c4-90b2-422f-b288-5a84b242c0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password input</value>
      <webElementGuid>17d581a9-057b-422e-b199-401e4ca930ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i7065ec41-05fc-11ef-adb4-ed4d7a2bca11&quot;)</value>
      <webElementGuid>fc035568-b6f8-4af3-b8bd-bc29770cbee1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i7065ec41-05fc-11ef-adb4-ed4d7a2bca11']</value>
      <webElementGuid>89b9ae2a-6401-4fb4-a058-6bd9d084056e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i7065ec41-05fc-11ef-adb4-ed4d7a2bca11-row']/div[2]/div/div/input</value>
      <webElementGuid>2985da17-3d75-458e-bb68-f347490a54ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>56015d88-2aea-4a61-9c21-2916edb508c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'i7065ec41-05fc-11ef-adb4-ed4d7a2bca11' and @name = 'password']</value>
      <webElementGuid>0ebbb370-5776-462f-9aa4-e24011154a31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
