<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_UserEmail</name>
   <tag></tag>
   <elementGuidId>a2d4ebf0-b483-44df-a27c-ee92fb3b3b36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i70659e21-05fc-11ef-adb4-ed4d7a2bca11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='i70659e21-05fc-11ef-adb4-ed4d7a2bca11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email input&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22014174-f9a5-4f64-a406-93faf1987c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87221716-c683-4aab-9299-841781d0ab51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i70659e21-05fc-11ef-adb4-ed4d7a2bca11</value>
      <webElementGuid>57ea6a04-4333-4644-b3c8-cdb2dacdafae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>0214c858-250a-4f07-9f67-d85a8aabf360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldText</value>
      <webElementGuid>2d85ff16-3561-4f6b-a3a8-c92ecd9c2815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email input</value>
      <webElementGuid>8475a557-fd33-4087-b7a0-55b28a11a704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i70659e21-05fc-11ef-adb4-ed4d7a2bca11&quot;)</value>
      <webElementGuid>ba58a405-5169-4b60-994c-8f503c0e5a51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i70659e21-05fc-11ef-adb4-ed4d7a2bca11']</value>
      <webElementGuid>f66669b3-aa40-4a0d-ab6c-2b2a20763678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i70659e21-05fc-11ef-adb4-ed4d7a2bca11-row']/div[2]/div/div/input</value>
      <webElementGuid>174449ec-33fd-4a38-9824-4fc7f6638a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c5105b3c-43da-4645-a54b-00f567ba1e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'i70659e21-05fc-11ef-adb4-ed4d7a2bca11' and @name = 'email']</value>
      <webElementGuid>0db2bd26-5b11-418b-9ba1-c40eb7d2d91f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
