<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text_LoginFailed</name>
   <tag></tag>
   <elementGuidId>dd7f3265-a6b9-4b1a-8302-59cea83166c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.euiCallOutHeader__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Login failed.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9a907d85-39f6-4485-99b1-1f3970cf1453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiCallOutHeader__title</value>
      <webElementGuid>c1e8d67f-9a47-4b61-b61f-7b6044c0f4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login failed.</value>
      <webElementGuid>16a889ba-c610-4fbf-835c-c600e7347bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;euiPage euiPage--paddingMedium euiPage--grow&quot;]/div[@class=&quot;euiPageBody euiPageBody--borderRadiusNone&quot;]/div[@class=&quot;euiPanel euiPanel--paddingLarge euiPanel--borderRadiusMedium euiPanel--plain euiPanel--hasShadow euiPageContent euiPageContent--verticalCenter euiPageContent--horizontalCenter&quot;]/div[@class=&quot;euiPageContentBody&quot;]/div[@class=&quot;euiCallOut euiCallOut--danger&quot;]/div[@class=&quot;euiCallOutHeader&quot;]/span[@class=&quot;euiCallOutHeader__title&quot;]</value>
      <webElementGuid>1665723e-7ca7-4f44-b668-1599f4cca261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div[3]/div/div/span</value>
      <webElementGuid>0c285b83-4136-4aa2-9d87-ac7daa2a7368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/preceding::span[1]</value>
      <webElementGuid>a36adc31-12a8-4af9-8d12-d68947c75fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::span[1]</value>
      <webElementGuid>e0250748-c3c1-4af6-8c82-ef9f712f1ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login failed.']/parent::*</value>
      <webElementGuid>52f9edeb-b993-49cf-a065-514897b63655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span</value>
      <webElementGuid>a2b8fcc9-7e16-4940-ac86-6367ddb0fa46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login failed.' or . = 'Login failed.')]</value>
      <webElementGuid>d92ccac5-0586-44b7-aa78-35fc0ec2a6a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
