<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_No restrictions (Public)</name>
   <tag></tag>
   <elementGuidId>b6ecf078-68da-4ba8-8938-5b28a6e544c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.euiSuperSelectControl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Public&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee9e580c-5ae2-4653-b513-d119bc05b5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a10af86-dee0-4475-aebc-fe58a9b01960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiSuperSelectControl</value>
      <webElementGuid>dab6cc99-4e88-488c-a256-a6566e52e69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>9d9848ce-7b11-4370-983c-254a705c176c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Public</value>
      <webElementGuid>3165bcdd-f053-4979-b983-2b10b09a8b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No restrictions (Public)</value>
      <webElementGuid>2f9f5fa4-de7c-453d-b4c8-18768c1651e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i89dcac11-0622-11ef-a415-3f41dc58ede6-row&quot;)/div[@class=&quot;euiFormRow__fieldWrapper&quot;]/div[@class=&quot;euiPopover euiPopover--anchorDownLeft euiPopover--displayBlock euiInputPopover euiSuperSelect&quot;]/div[@class=&quot;euiPopover__anchor&quot;]/div[1]/div[@class=&quot;euiFormControlLayout&quot;]/div[@class=&quot;euiFormControlLayout__childrenWrapper&quot;]/button[@class=&quot;euiSuperSelectControl&quot;]</value>
      <webElementGuid>212d261c-a853-45f6-b996-b0393e5ea058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>9ad35c5f-0ac9-4c1b-9677-6dbbb26e2b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i89dcac11-0622-11ef-a415-3f41dc58ede6-row']/div/div/div/div/div/div/button</value>
      <webElementGuid>0f80f96c-f5a4-49cc-b00f-c4bf6e7c69b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an option: No restrictions (Public), is selected'])[1]/following::button[1]</value>
      <webElementGuid>fef7091a-d6e8-4876-a7fe-9d5f2992a91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access Request'])[1]/following::button[1]</value>
      <webElementGuid>2040f678-9397-4461-ab9c-1aad603d61bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results Table'])[1]/preceding::button[1]</value>
      <webElementGuid>809adba3-1f78-447a-9b40-8aa608292a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload File'])[1]/preceding::button[2]</value>
      <webElementGuid>4b05dec2-e146-42a9-ae28-fc679d3d46ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No restrictions (Public)']/parent::*</value>
      <webElementGuid>6c293df0-6d2e-40d3-a004-659b89d58c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/button</value>
      <webElementGuid>014b83bd-c04b-4059-bd5c-352daba9dfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'No restrictions (Public)' or . = 'No restrictions (Public)')]</value>
      <webElementGuid>8442c20c-ba41-4971-917d-fd8bc486f333</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
