<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown_2K</name>
   <tag></tag>
   <elementGuidId>16a442a9-f47e-4c3c-8971-0e122d709408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i858c6f50-0623-11ef-b58b-3f8fcae67c47__option-2 > span.euiFlexGroup.euiFlexGroup--gutterSmall.euiFlexGroup--alignItemsCenter.euiFlexGroup--directionRow > span.euiFlexItem.euiFilterSelectItem__content > span.euiComboBoxOption__contentWrapper > span.euiComboBoxOption__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='i858c6f50-0623-11ef-b58b-3f8fcae67c47__option-2']/span/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;2K&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7bb22c7b-2c4f-4b09-a07f-a2563c81bd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiComboBoxOption__content</value>
      <webElementGuid>fddc58de-240f-4f08-8393-773b8bdf4d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2K</value>
      <webElementGuid>3fdadeb6-606f-4823-b5db-cdecc449d9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i858c6f50-0623-11ef-b58b-3f8fcae67c47__option-2&quot;)/span[@class=&quot;euiFlexGroup euiFlexGroup--gutterSmall euiFlexGroup--alignItemsCenter euiFlexGroup--directionRow&quot;]/span[@class=&quot;euiFlexItem euiFilterSelectItem__content&quot;]/span[@class=&quot;euiComboBoxOption__contentWrapper&quot;]/span[@class=&quot;euiComboBoxOption__content&quot;]</value>
      <webElementGuid>751b8314-0da2-49d3-aa43-ea6f30b26254</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='i858c6f50-0623-11ef-b58b-3f8fcae67c47__option-2']/span/span/span/span</value>
      <webElementGuid>96a2600d-9d79-4b13-ac29-f0859b7cf692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single image test no results table with Ignore mask 1'])[1]/following::span[4]</value>
      <webElementGuid>c6c31126-71c8-41da-a894-b3bc1481430e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::span[12]</value>
      <webElementGuid>33e17d0f-4747-4694-a805-3cced4a8fc55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mixed'])[1]/preceding::span[1]</value>
      <webElementGuid>22d2241f-4dc1-4c30-892f-1dc815ea5e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Focus Mask Test'])[1]/preceding::span[5]</value>
      <webElementGuid>96498f58-930f-4f82-a2ec-4fa8304188dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2K']/parent::*</value>
      <webElementGuid>6630e1a8-dc7e-4b8e-8940-cff706840e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/span/span/span/span</value>
      <webElementGuid>c0e908e0-f8e8-4fa8-b2e5-8999fdd55f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '2K' or . = '2K')]</value>
      <webElementGuid>f0c5e331-c757-43ca-b3f8-515b5cdd6bb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
