<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User_email</name>
   <tag></tag>
   <elementGuidId>92f18a50-4b8e-435b-a1da-b5c06ee11861</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i79930e31-0622-11ef-a415-3f41dc58ede6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='i79930e31-0622-11ef-a415-3f41dc58ede6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email input&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>987f0ea0-ede3-4807-9590-c4468860a8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d933dffd-23c9-40a3-8a7f-50c76f39480b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i79930e31-0622-11ef-a415-3f41dc58ede6</value>
      <webElementGuid>113a5cdf-49b9-4e5d-93c1-36b5785b9273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>7a955015-46d0-4268-8e12-6203711aa284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldText</value>
      <webElementGuid>45993d41-7055-4151-9292-f525edd09fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email input</value>
      <webElementGuid>3ea96069-6212-4d90-83c9-c3f579cd4fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i79930e31-0622-11ef-a415-3f41dc58ede6&quot;)</value>
      <webElementGuid>502458a4-7f42-483e-ad76-d27dcdc790d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i79930e31-0622-11ef-a415-3f41dc58ede6']</value>
      <webElementGuid>3cb3b951-854d-4b05-864f-c5885aaaf2b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i79930e31-0622-11ef-a415-3f41dc58ede6-row']/div[2]/div/div/input</value>
      <webElementGuid>c799398b-4162-4ac1-b779-3a6ec45be5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ceef0c1f-c357-4364-9d48-4faeb52ee601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'i79930e31-0622-11ef-a415-3f41dc58ede6' and @name = 'email']</value>
      <webElementGuid>bdb70476-50f8-4803-88b0-bc4e86d10427</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
