<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please note that, only one Product Ti_ef8aab</name>
   <tag></tag>
   <elementGuidId>97995baa-a8d6-4791-827e-474c513f6c23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i89dc36e0-0622-11ef-a415-3f41dc58ede6__eui-combobox-id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='i89dc36e0-0622-11ef-a415-3f41dc58ede6__eui-combobox-id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select or create a Title&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>052f37b7-dd18-4d1f-8e38-b03150eef521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select or create a Title</value>
      <webElementGuid>e823df9d-3d75-4638-821f-7941388dc32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>i89dc36e0-0622-11ef-a415-3f41dc58ede6_listbox</value>
      <webElementGuid>50600eb7-b656-4dd0-b1fb-1fb3275ca9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-subj</name>
      <type>Main</type>
      <value>comboBoxSearchInput</value>
      <webElementGuid>9ef6b6e9-e7fa-4322-941d-71e585ac75ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i89dc36e0-0622-11ef-a415-3f41dc58ede6__eui-combobox-id</value>
      <webElementGuid>3595f381-3076-469b-960a-618123bcca7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>dec10a3f-814c-4c61-b334-f9e6ac1d55f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>d</value>
      <webElementGuid>c962776e-a1f3-4c40-8fba-87b907bb4da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i89dc36e0-0622-11ef-a415-3f41dc58ede6__eui-combobox-id&quot;)</value>
      <webElementGuid>846ea181-e6f6-4f36-a893-71cd96e57426</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i89dc36e0-0622-11ef-a415-3f41dc58ede6__eui-combobox-id']</value>
      <webElementGuid>469ade45-3ed3-4426-8f49-354ca8f4800a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i89dbe8c3-0622-11ef-a415-3f41dc58ede6-row']/div/div/div/div/div/div/input</value>
      <webElementGuid>c7435ef2-f7d7-4e51-9322-20a0ccf9f993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>e982bc63-500a-478a-91e7-0449496e2196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'i89dc36e0-0622-11ef-a415-3f41dc58ede6__eui-combobox-id']</value>
      <webElementGuid>b9f7b074-8ca7-4926-aa4a-d65b6a4efc12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
