<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>3ac2416f-3448-4114-86e9-e81bc7b3e703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i79935c51-0622-11ef-a415-3f41dc58ede6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='i79935c51-0622-11ef-a415-3f41dc58ede6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Password input&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60f92394-34c0-4e8a-9591-b86c3dcde678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>70f10df7-539f-447f-9ad1-25bccd8d6811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i79935c51-0622-11ef-a415-3f41dc58ede6</value>
      <webElementGuid>3648602f-5740-4023-8e34-8f5f9ea6cbca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d4bdd233-ef96-43b6-88c3-abdd8ae23cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldPassword</value>
      <webElementGuid>eadcba70-2152-4746-825b-29a82d7ec3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password input</value>
      <webElementGuid>3edad9a6-7438-494f-97f4-d63101e915d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i79935c51-0622-11ef-a415-3f41dc58ede6&quot;)</value>
      <webElementGuid>ff0527ed-345d-48be-953a-910453f30051</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i79935c51-0622-11ef-a415-3f41dc58ede6']</value>
      <webElementGuid>4665f29b-9f2f-4ea6-9676-348cc1e5dfbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i79935c51-0622-11ef-a415-3f41dc58ede6-row']/div[2]/div/div/input</value>
      <webElementGuid>05cc74ee-8071-419f-b7f5-7fec193c8d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>515edb92-c1db-491f-b219-37fb23461155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'i79935c51-0622-11ef-a415-3f41dc58ede6' and @name = 'password']</value>
      <webElementGuid>22b2a57d-06f0-401a-96e8-b435b40d1179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
