<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_UserRestriction_AddUserEmail</name>
   <tag></tag>
   <elementGuidId>4b5a7fe6-b53c-4a6b-b0ab-66e87b233c03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.euiFieldText.focusableEmail.euiFieldText--withIcon.euiFieldText--compressed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;someone@ea.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1523ef51-6d05-4e69-aa7b-f9efe46ccd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>671e0ae7-cddb-47ea-90c9-0098275712e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>someone@ea.com</value>
      <webElementGuid>1ea56d4c-52fa-4920-885e-32a92287a073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldText focusableEmail euiFieldText--withIcon euiFieldText--compressed</value>
      <webElementGuid>5ba616cd-a7b2-4ac1-bb80-c8705563ea28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i5aacee91-0614-11ef-aa66-f77cc2878ce2-row&quot;)/div[@class=&quot;euiFormRow__fieldWrapper&quot;]/div[@class=&quot;euiFormControlLayout euiFormControlLayout--compressed&quot;]/div[@class=&quot;euiFormControlLayout__childrenWrapper&quot;]/input[@class=&quot;euiFieldText focusableEmail euiFieldText--withIcon euiFieldText--compressed&quot;]</value>
      <webElementGuid>9d521a32-fe0b-4250-9981-31090fe47061</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[3]</value>
      <webElementGuid>38cab7da-7f77-40f4-98cf-df85213d6543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i5aacee91-0614-11ef-aa66-f77cc2878ce2-row']/div[2]/div/div/input</value>
      <webElementGuid>2dfbbbd7-b8e0-4bc2-81c8-c27a865a425b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>6b5a9582-043c-4369-bf1e-dd96eecec651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'someone@ea.com']</value>
      <webElementGuid>bcba5257-2543-4f0c-847a-cd2966812331</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
