<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_AddRequest Name</name>
   <tag></tag>
   <elementGuidId>eb205725-3d52-41bb-8c99-c4b6ecddde3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ibbbd37e1-0613-11ef-aa66-f77cc2878ce2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ibbbd37e1-0613-11ef-aa66-f77cc2878ce2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Request name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfc2a89b-efbd-4179-a593-575f0a7899ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76caffa8-19e6-4361-ac72-6aa6fc25cfa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ibbbd37e1-0613-11ef-aa66-f77cc2878ce2</value>
      <webElementGuid>580c94a9-2dfc-4b59-9779-a91b88177c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RequestName</value>
      <webElementGuid>0551b451-636e-48e3-8eb4-f4d1854b7d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldText</value>
      <webElementGuid>97e8dbad-b0cc-465d-afdc-553c25d6d1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Request name</value>
      <webElementGuid>276fa8fd-da1b-44df-a761-52d354902639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ibbbd37e1-0613-11ef-aa66-f77cc2878ce2&quot;)</value>
      <webElementGuid>a09837fa-34b0-4ecc-8557-d40ceb6337f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ibbbd37e1-0613-11ef-aa66-f77cc2878ce2']</value>
      <webElementGuid>78d4f56b-6b4e-4a73-9205-eb69a7d49305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ibbbd37e1-0613-11ef-aa66-f77cc2878ce2-row']/div/div/div/input</value>
      <webElementGuid>5000d8f3-f2f0-4ef6-b22d-f5f4b8ac7d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b7c68843-30b8-4385-a074-9a94157841a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ibbbd37e1-0613-11ef-aa66-f77cc2878ce2' and @name = 'RequestName']</value>
      <webElementGuid>25249b14-584a-4c31-b9c4-833ed2e98ca1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
