<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_EnableResultsTable</name>
   <tag></tag>
   <elementGuidId>08678ead-b89d-4b20-b769-83b5bc575a14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ibbbdd425-0613-11ef-aa66-f77cc2878ce2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ibbbdd425-0613-11ef-aa66-f77cc2878ce2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>deb562f7-9ef2-4cf2-9c4f-a4359109f7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ibbbdd425-0613-11ef-aa66-f77cc2878ce2</value>
      <webElementGuid>d9f27c6b-9eda-4771-8a38-ec84256d6818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>33505361-8338-4b3f-944a-a116d4326031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiSwitch__button</value>
      <webElementGuid>ca57060a-4d60-4568-981d-2f334c7f4154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>3579ec1d-d296-44fd-b7c1-178b42e201fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29ed6aba-6443-40ed-83b3-aca9cd8979ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>ibbbdd427-0613-11ef-aa66-f77cc2878ce2</value>
      <webElementGuid>f6872c81-6a74-436b-b111-b4007722e3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ibbbdd425-0613-11ef-aa66-f77cc2878ce2&quot;)</value>
      <webElementGuid>d4b45039-b306-472b-9bff-a728bad45ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ibbbdd425-0613-11ef-aa66-f77cc2878ce2']</value>
      <webElementGuid>cb548eaf-c91c-410b-a3ee-3544586629e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ibbbdd423-0613-11ef-aa66-f77cc2878ce2-row']/div/div/button</value>
      <webElementGuid>1b47d409-dfca-412a-91ff-34f6733c762a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results Table'])[1]/following::button[1]</value>
      <webElementGuid>08d44caa-fc87-4578-becb-0c08190b95c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload File'])[1]/preceding::button[1]</value>
      <webElementGuid>fc5f1ff0-58d1-4726-b776-0503a76b88cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can upload one or more images or videos here.'])[1]/preceding::button[1]</value>
      <webElementGuid>5cdfde7b-a25f-4f5f-9829-43c125157341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/div/button</value>
      <webElementGuid>e74fc082-2e4b-4c39-a045-5667fe95c342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ibbbdd425-0613-11ef-aa66-f77cc2878ce2' and @type = 'button']</value>
      <webElementGuid>6dc2658b-4eba-4346-a5c3-f838bc51c8e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
