<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_UserRestrictions</name>
   <tag></tag>
   <elementGuidId>b5cc9312-afbe-40ff-8521-ae541f3bd939</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.euiSuperSelectControl.euiSuperSelect--isOpen__button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Public&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e8fcca53-0635-4f5e-843a-675f129d8c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9c15287-b731-407c-8d4a-36db57acf770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiSuperSelectControl euiSuperSelect--isOpen__button</value>
      <webElementGuid>accb6118-d052-453a-8229-55455bfaa5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>96660316-9ad8-4fae-b121-e533179ed41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Public</value>
      <webElementGuid>44767121-7761-4acb-8a68-85e4bec5469a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No restrictions (Public)</value>
      <webElementGuid>b7385898-a90a-41e2-8656-a0312d9468a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ibbbdad11-0613-11ef-aa66-f77cc2878ce2-row&quot;)/div[@class=&quot;euiFormRow__fieldWrapper&quot;]/div[@class=&quot;euiPopover euiPopover--anchorDownLeft euiPopover--displayBlock euiPopover-isOpen euiInputPopover euiSuperSelect&quot;]/div[@class=&quot;euiPopover__anchor&quot;]/div[1]/div[@class=&quot;euiFormControlLayout&quot;]/div[@class=&quot;euiFormControlLayout__childrenWrapper&quot;]/button[@class=&quot;euiSuperSelectControl euiSuperSelect--isOpen__button&quot;]</value>
      <webElementGuid>e68cb9bc-d667-420c-871d-7a79e7e07dad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>c5e03ade-a589-4417-a1a6-3cd237c5a588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ibbbdad11-0613-11ef-aa66-f77cc2878ce2-row']/div/div/div/div/div/div/button</value>
      <webElementGuid>6836abb9-9775-4e00-bb09-37d0b6a45667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an option: No restrictions (Public), is selected'])[1]/following::button[1]</value>
      <webElementGuid>178e4f3c-db21-4818-80b1-64c050ab5b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access Request'])[1]/following::button[1]</value>
      <webElementGuid>37d551ac-489e-4be5-b51e-4fbdf95809d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results Table'])[1]/preceding::button[1]</value>
      <webElementGuid>a66a223a-923e-428b-998e-2844d932aa65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload File'])[1]/preceding::button[2]</value>
      <webElementGuid>68b1903d-721e-4170-ae6f-a5035d717737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No restrictions (Public)']/parent::*</value>
      <webElementGuid>5f6edfa2-859b-438c-a8a4-f1b2f91e6007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/button</value>
      <webElementGuid>f6f6cc37-fef6-433f-92da-5e1929a4ffa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'No restrictions (Public)' or . = 'No restrictions (Public)')]</value>
      <webElementGuid>64ffa9cd-8280-42e6-b722-0cad6ea5a6d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
